<?php

namespace Database\Seeders;

use App\Models\Shared\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::create(['Alpha2Code' => 'AW', 'Alpha3Code' => 'ABW', 'NumericCode' => '533', 'Name' => 'Aruba', 'PhoneCode' => '297']);
        Country::create(['Alpha2Code' => 'AF', 'Alpha3Code' => 'AFG', 'NumericCode' => '4', 'Name' => 'Afganistán', 'PhoneCode' => '93']);
        Country::create(['Alpha2Code' => 'AO', 'Alpha3Code' => 'AGO', 'NumericCode' => '24', 'Name' => 'Angola', 'PhoneCode' => '244']);
        Country::create(['Alpha2Code' => 'AI', 'Alpha3Code' => 'AIA', 'NumericCode' => '660', 'Name' => 'Anguilla', 'PhoneCode' => '1-264']);
        Country::create(['Alpha2Code' => 'AL', 'Alpha3Code' => 'ALB', 'NumericCode' => '8', 'Name' => 'Albania', 'PhoneCode' => '355']);
        Country::create(['Alpha2Code' => 'AD', 'Alpha3Code' => 'AND', 'NumericCode' => '20', 'Name' => 'Andorra', 'PhoneCode' => '376']);
        Country::create(['Alpha2Code' => 'AE', 'Alpha3Code' => 'ARE', 'NumericCode' => '784', 'Name' => 'Emiratos árabes Unidos', 'PhoneCode' => '971']);
        Country::create(['Alpha2Code' => 'AR', 'Alpha3Code' => 'ARG', 'NumericCode' => '32', 'Name' => 'Argentina', 'PhoneCode' => '54']);
        Country::create(['Alpha2Code' => 'AM', 'Alpha3Code' => 'ARM', 'NumericCode' => '51', 'Name' => 'Armenia', 'PhoneCode' => '374']);
        Country::create(['Alpha2Code' => 'AS', 'Alpha3Code' => 'ASM', 'NumericCode' => '16', 'Name' => 'Samoa Americana', 'PhoneCode' => '1-684']);
        Country::create(['Alpha2Code' => 'AQ', 'Alpha3Code' => 'ATA', 'NumericCode' => '10', 'Name' => 'Antártida', 'PhoneCode' => '672']);
        Country::create(['Alpha2Code' => 'TF', 'Alpha3Code' => 'ATF', 'NumericCode' => '260', 'Name' => 'Tierras Australes y Antárticas Francesas', 'PhoneCode' => '262']);
        Country::create(['Alpha2Code' => 'AG', 'Alpha3Code' => 'ATG', 'NumericCode' => '28', 'Name' => 'Antigua y Barbuda', 'PhoneCode' => '1-268']);
        Country::create(['Alpha2Code' => 'AU', 'Alpha3Code' => 'AUS', 'NumericCode' => '36', 'Name' => 'Australia', 'PhoneCode' => '61']);
        Country::create(['Alpha2Code' => 'AT', 'Alpha3Code' => 'AUT', 'NumericCode' => '40', 'Name' => 'Austria', 'PhoneCode' => '43']);
        Country::create(['Alpha2Code' => 'AZ', 'Alpha3Code' => 'AZE', 'NumericCode' => '31', 'Name' => 'Azerbaiyán', 'PhoneCode' => '994']);
        Country::create(['Alpha2Code' => 'BI', 'Alpha3Code' => 'BDI', 'NumericCode' => '108', 'Name' => 'Burundi', 'PhoneCode' => '257']);
        Country::create(['Alpha2Code' => 'BE', 'Alpha3Code' => 'BEL', 'NumericCode' => '56', 'Name' => 'Belgica', 'PhoneCode' => '32']);
        Country::create(['Alpha2Code' => 'BJ', 'Alpha3Code' => 'BEN', 'NumericCode' => '204', 'Name' => 'Benin', 'PhoneCode' => '229']);
        Country::create(['Alpha2Code' => 'BQ', 'Alpha3Code' => 'BES', 'NumericCode' => '535', 'Name' => 'Caribe Neerlandés', 'PhoneCode' => '599']);
        Country::create(['Alpha2Code' => 'BF', 'Alpha3Code' => 'BFA', 'NumericCode' => '854', 'Name' => 'Burkina Faso', 'PhoneCode' => '226']);
        Country::create(['Alpha2Code' => 'BD', 'Alpha3Code' => 'BGD', 'NumericCode' => '50', 'Name' => 'Bangladés', 'PhoneCode' => '880']);
        Country::create(['Alpha2Code' => 'BG', 'Alpha3Code' => 'BGR', 'NumericCode' => '100', 'Name' => 'Bulgaria', 'PhoneCode' => '359']);
        Country::create(['Alpha2Code' => 'BH', 'Alpha3Code' => 'BHR', 'NumericCode' => '48', 'Name' => 'Baréin', 'PhoneCode' => '973']);
        Country::create(['Alpha2Code' => 'BS', 'Alpha3Code' => 'BHS', 'NumericCode' => '44', 'Name' => 'Bahamas', 'PhoneCode' => '1-242']);
        Country::create(['Alpha2Code' => 'BA', 'Alpha3Code' => 'BIH', 'NumericCode' => '70', 'Name' => 'Bosnia y Herzegovina', 'PhoneCode' => '387']);
        Country::create(['Alpha2Code' => 'BL', 'Alpha3Code' => 'BLM', 'NumericCode' => '652', 'Name' => 'San Bartolomé', 'PhoneCode' => '590']);
        Country::create(['Alpha2Code' => 'BY', 'Alpha3Code' => 'BLR', 'NumericCode' => '112', 'Name' => 'Bielorussia', 'PhoneCode' => '375']);
        Country::create(['Alpha2Code' => 'BZ', 'Alpha3Code' => 'BLZ', 'NumericCode' => '84', 'Name' => 'Belice', 'PhoneCode' => '501']);
        Country::create(['Alpha2Code' => 'BM', 'Alpha3Code' => 'BMU', 'NumericCode' => '60', 'Name' => 'Bermudas', 'PhoneCode' => '1-441']);
        Country::create(['Alpha2Code' => 'BO', 'Alpha3Code' => 'BOL', 'NumericCode' => '68', 'Name' => 'Bolivia', 'PhoneCode' => '591']);
        Country::create(['Alpha2Code' => 'BR', 'Alpha3Code' => 'BRA', 'NumericCode' => '76', 'Name' => 'Brasil', 'PhoneCode' => '55']);
        Country::create(['Alpha2Code' => 'BB', 'Alpha3Code' => 'BRB', 'NumericCode' => '52', 'Name' => 'Barbados', 'PhoneCode' => '1-246']);
        Country::create(['Alpha2Code' => 'BN', 'Alpha3Code' => 'BRN', 'NumericCode' => '96', 'Name' => 'Brunéi', 'PhoneCode' => '673']);
        Country::create(['Alpha2Code' => 'BT', 'Alpha3Code' => 'BTN', 'NumericCode' => '64', 'Name' => 'Bután', 'PhoneCode' => '975']);
        Country::create(['Alpha2Code' => 'BW', 'Alpha3Code' => 'BWA', 'NumericCode' => '72', 'Name' => 'Botsuana', 'PhoneCode' => '267']);
        Country::create(['Alpha2Code' => 'CF', 'Alpha3Code' => 'CAF', 'NumericCode' => '140', 'Name' => 'República Centroafricana', 'PhoneCode' => '236']);
        Country::create(['Alpha2Code' => 'CA', 'Alpha3Code' => 'CAN', 'NumericCode' => '124', 'Name' => 'Canadá', 'PhoneCode' => '1']);
        Country::create(['Alpha2Code' => 'CC', 'Alpha3Code' => 'CCK', 'NumericCode' => '166', 'Name' => 'Islas Cocos', 'PhoneCode' => '61']);
        Country::create(['Alpha2Code' => 'CH', 'Alpha3Code' => 'CHE', 'NumericCode' => '756', 'Name' => 'Suiza', 'PhoneCode' => '41']);
        Country::create(['Alpha2Code' => 'CL', 'Alpha3Code' => 'CHL', 'NumericCode' => '152', 'Name' => 'Chile', 'PhoneCode' => '56']);
        Country::create(['Alpha2Code' => 'CN', 'Alpha3Code' => 'CHN', 'NumericCode' => '156', 'Name' => 'China', 'PhoneCode' => '86']);
        Country::create(['Alpha2Code' => 'CI', 'Alpha3Code' => 'CIV', 'NumericCode' => '384', 'Name' => 'Costa de Marfil', 'PhoneCode' => '225']);
        Country::create(['Alpha2Code' => 'CM', 'Alpha3Code' => 'CMR', 'NumericCode' => '120', 'Name' => 'Camerún', 'PhoneCode' => '237']);
        Country::create(['Alpha2Code' => 'CD', 'Alpha3Code' => 'COD', 'NumericCode' => '180', 'Name' => 'República Democrática del Congo', 'PhoneCode' => '243']);
        Country::create(['Alpha2Code' => 'CG', 'Alpha3Code' => 'COG', 'NumericCode' => '178', 'Name' => 'República del Congo', 'PhoneCode' => '242']);
        Country::create(['Alpha2Code' => 'CK', 'Alpha3Code' => 'COK', 'NumericCode' => '184', 'Name' => 'Islas Cook', 'PhoneCode' => '682']);
        Country::create(['Alpha2Code' => 'CO', 'Alpha3Code' => 'COL', 'NumericCode' => '170', 'Name' => 'Colombia', 'PhoneCode' => '57']);
        Country::create(['Alpha2Code' => 'KM', 'Alpha3Code' => 'COM', 'NumericCode' => '174', 'Name' => 'Comoras', 'PhoneCode' => '269']);
        Country::create(['Alpha2Code' => 'CV', 'Alpha3Code' => 'CPV', 'NumericCode' => '132', 'Name' => 'Cabo Verde', 'PhoneCode' => '238']);
        Country::create(['Alpha2Code' => 'CR', 'Alpha3Code' => 'CRI', 'NumericCode' => '188', 'Name' => 'Costa Rica', 'PhoneCode' => '506']);
        Country::create(['Alpha2Code' => 'CU', 'Alpha3Code' => 'CUB', 'NumericCode' => '192', 'Name' => 'Cuba', 'PhoneCode' => '53']);
        Country::create(['Alpha2Code' => 'CW', 'Alpha3Code' => 'CUW', 'NumericCode' => '531', 'Name' => 'Curazao'   , 'PhoneCode' => '599']);
        Country::create(['Alpha2Code' => 'CX', 'Alpha3Code' => 'CXR', 'NumericCode' => '162', 'Name' => 'Isla de Navidad', 'PhoneCode' => '61']);
        Country::create(['Alpha2Code' => 'KY', 'Alpha3Code' => 'CYM', 'NumericCode' => '136', 'Name' => 'Islas Caimán', 'PhoneCode' => '1-345']);
        Country::create(['Alpha2Code' => 'CY', 'Alpha3Code' => 'CYP', 'NumericCode' => '196', 'Name' => 'Chipre', 'PhoneCode' => '357']);
        Country::create(['Alpha2Code' => 'CZ', 'Alpha3Code' => 'CZE', 'NumericCode' => '203', 'Name' => 'República Checa', 'PhoneCode' => '420']);
        Country::create(['Alpha2Code' => 'DE', 'Alpha3Code' => 'DEU', 'NumericCode' => '276', 'Name' => 'Alemania', 'PhoneCode' => '49']);
        Country::create(['Alpha2Code' => 'DJ', 'Alpha3Code' => 'DJI', 'NumericCode' => '262', 'Name' => 'Yibuti', 'PhoneCode' => '253']);
        Country::create(['Alpha2Code' => 'DM', 'Alpha3Code' => 'DMA', 'NumericCode' => '212', 'Name' => 'Dominica', 'PhoneCode' => '1-767']);
        Country::create(['Alpha2Code' => 'DK', 'Alpha3Code' => 'DNK', 'NumericCode' => '208', 'Name' => 'Dinamarca', 'PhoneCode' => '45']);
        Country::create(['Alpha2Code' => 'DO', 'Alpha3Code' => 'DOM', 'NumericCode' => '214', 'Name' => 'República Dominicana', 'PhoneCode' => '1-809']);
        Country::create(['Alpha2Code' => 'DZ', 'Alpha3Code' => 'DZA', 'NumericCode' => '12', 'Name' => 'Argelia', 'PhoneCode' => '213']);
        Country::create(['Alpha2Code' => 'EC', 'Alpha3Code' => 'ECU', 'NumericCode' => '218', 'Name' => 'Ecuador', 'PhoneCode' => '593']);
        Country::create(['Alpha2Code' => 'EG', 'Alpha3Code' => 'EGY', 'NumericCode' => '818', 'Name' => 'Egipto', 'PhoneCode' => '20']);
        Country::create(['Alpha2Code' => 'ER', 'Alpha3Code' => 'ERI', 'NumericCode' => '232', 'Name' => 'Eritrea', 'PhoneCode' => '291']);
        Country::create(['Alpha2Code' => 'EH', 'Alpha3Code' => 'ESH', 'NumericCode' => '732', 'Name' => 'República árabe Saharaui Democrática', 'PhoneCode' => '212']);
        Country::create(['Alpha2Code' => 'ES', 'Alpha3Code' => 'ESP', 'NumericCode' => '724', 'Name' => 'España', 'PhoneCode' => '34']);
        Country::create(['Alpha2Code' => 'EE', 'Alpha3Code' => 'EST', 'NumericCode' => '233', 'Name' => 'Estonia', 'PhoneCode' => '372']);
        Country::create(['Alpha2Code' => 'ET', 'Alpha3Code' => 'ETH', 'NumericCode' => '231', 'Name' => 'Etiopía', 'PhoneCode' => '251']);
        Country::create(['Alpha2Code' => 'FI', 'Alpha3Code' => 'FIN', 'NumericCode' => '246', 'Name' => 'Finlandia', 'PhoneCode' => '358']);
        Country::create(['Alpha2Code' => 'FJ', 'Alpha3Code' => 'FJI', 'NumericCode' => '242', 'Name' => 'Fiyi', 'PhoneCode' => '679']);
        Country::create(['Alpha2Code' => 'FK', 'Alpha3Code' => 'FLK', 'NumericCode' => '238', 'Name' => 'Islas Malvinas'    , 'PhoneCode' => '500']);
        Country::create(['Alpha2Code' => 'FR', 'Alpha3Code' => 'FRA', 'NumericCode' => '250', 'Name' => 'Francia', 'PhoneCode' => '33']);
        Country::create(['Alpha2Code' => 'FO', 'Alpha3Code' => 'FRO', 'NumericCode' => '234', 'Name' => 'Islas Feroe', 'PhoneCode' => '298']);
        Country::create(['Alpha2Code' => 'FM', 'Alpha3Code' => 'FSM', 'NumericCode' => '583', 'Name' => 'Estados Federados de Micronesia', 'PhoneCode' => '691']);
        Country::create(['Alpha2Code' => 'GA', 'Alpha3Code' => 'GAB', 'NumericCode' => '266', 'Name' => 'Gabon', 'PhoneCode' => '241']);
        Country::create(['Alpha2Code' => 'GB', 'Alpha3Code' => 'GBR', 'NumericCode' => '826', 'Name' => 'Reino Unido', 'PhoneCode' => '44']);
        Country::create(['Alpha2Code' => 'GE', 'Alpha3Code' => 'GEO', 'NumericCode' => '268', 'Name' => 'Georgia', 'PhoneCode' => '995']);
        Country::create(['Alpha2Code' => 'GG', 'Alpha3Code' => 'GGY', 'NumericCode' => '831', 'Name' => 'Guernsey', 'PhoneCode' => '44']);
        Country::create(['Alpha2Code' => 'GH', 'Alpha3Code' => 'GHA', 'NumericCode' => '288', 'Name' => 'Ghana', 'PhoneCode' => '233']);
        Country::create(['Alpha2Code' => 'GI', 'Alpha3Code' => 'GIB', 'NumericCode' => '292', 'Name' => 'Gibraltar', 'PhoneCode' => '350']);
        Country::create(['Alpha2Code' => 'GN', 'Alpha3Code' => 'GIN', 'NumericCode' => '324', 'Name' => 'Guinea', 'PhoneCode' => '224']);
        Country::create(['Alpha2Code' => 'GP', 'Alpha3Code' => 'GLP', 'NumericCode' => '312', 'Name' => 'Guadelupe', 'PhoneCode' => '590']);
        Country::create(['Alpha2Code' => 'GM', 'Alpha3Code' => 'GMB', 'NumericCode' => '270', 'Name' => 'Gambia', 'PhoneCode' => '220']);
        Country::create(['Alpha2Code' => 'GW', 'Alpha3Code' => 'GNB', 'NumericCode' => '624', 'Name' => 'Guinea-Bissau', 'PhoneCode' => '245']);
        Country::create(['Alpha2Code' => 'GQ', 'Alpha3Code' => 'GNQ', 'NumericCode' => '226', 'Name' => 'Guinea Ecuatorial', 'PhoneCode' => '240']);
        Country::create(['Alpha2Code' => 'GR', 'Alpha3Code' => 'GRC', 'NumericCode' => '300', 'Name' => 'Grecia', 'PhoneCode' => '30']);
        Country::create(['Alpha2Code' => 'GD', 'Alpha3Code' => 'GRD', 'NumericCode' => '308', 'Name' => 'Granada', 'PhoneCode' => '1-473']);
        Country::create(['Alpha2Code' => 'GL', 'Alpha3Code' => 'GRL', 'NumericCode' => '304', 'Name' => 'Groenlandia', 'PhoneCode' => '299']);
        Country::create(['Alpha2Code' => 'GT', 'Alpha3Code' => 'GTM', 'NumericCode' => '320', 'Name' => 'Guatemala', 'PhoneCode' => '502']);
        Country::create(['Alpha2Code' => 'GF', 'Alpha3Code' => 'GUF', 'NumericCode' => '254', 'Name' => 'Guayana Francesa', 'PhoneCode' => '594']);
        Country::create(['Alpha2Code' => 'GU', 'Alpha3Code' => 'GUM', 'NumericCode' => '316', 'Name' => 'Guam'  , 'PhoneCode' => '1-671']);
        Country::create(['Alpha2Code' => 'GY', 'Alpha3Code' => 'GUY', 'NumericCode' => '328', 'Name' => 'Guyana', 'PhoneCode' => '592']);
        Country::create(['Alpha2Code' => 'HK', 'Alpha3Code' => 'HKG', 'NumericCode' => '344', 'Name' => 'Hong Kong', 'PhoneCode' => '852']);
        Country::create(['Alpha2Code' => 'HN', 'Alpha3Code' => 'HND', 'NumericCode' => '340', 'Name' => 'Honduras', 'PhoneCode' => '504']);
        Country::create(['Alpha2Code' => 'HR', 'Alpha3Code' => 'HRV', 'NumericCode' => '191', 'Name' => 'Croacia', 'PhoneCode' => '385']);
        Country::create(['Alpha2Code' => 'HT', 'Alpha3Code' => 'HTI', 'NumericCode' => '332', 'Name' => 'Haití', 'PhoneCode' => '509']);
        Country::create(['Alpha2Code' => 'HU', 'Alpha3Code' => 'HUN', 'NumericCode' => '348', 'Name' => 'Hungría', 'PhoneCode' => '36']);
        Country::create(['Alpha2Code' => 'ID', 'Alpha3Code' => 'IDN', 'NumericCode' => '360', 'Name' => 'Indonesia', 'PhoneCode' => '62']);
        Country::create(['Alpha2Code' => 'IM', 'Alpha3Code' => 'IMN', 'NumericCode' => '833', 'Name' => 'Isla de Man', 'PhoneCode' => '44']);
        Country::create(['Alpha2Code' => 'IN', 'Alpha3Code' => 'IND', 'NumericCode' => '356', 'Name' => 'India', 'PhoneCode' => '91']);
        Country::create(['Alpha2Code' => 'IO', 'Alpha3Code' => 'IOT', 'NumericCode' => '86', 'Name' => 'Territorio Británico del Océano índi<co', 'PhoneCode' => '246']);
        Country::create(['Alpha2Code' => 'IE', 'Alpha3Code' => 'IRL', 'NumericCode' => '372', 'Name' => 'Islandia', 'PhoneCode' => '354']);
        Country::create(['Alpha2Code' => 'IR', 'Alpha3Code' => 'IRN', 'NumericCode' => '364', 'Name' => 'Iran', 'PhoneCode' => '98']);
        Country::create(['Alpha2Code' => 'IQ', 'Alpha3Code' => 'IRQ', 'NumericCode' => '368', 'Name' => 'Irak', 'PhoneCode' => '964']);
        Country::create(['Alpha2Code' => 'IS', 'Alpha3Code' => 'ISL', 'NumericCode' => '352', 'Name' => 'Iceland', 'PhoneCode' => '354']);
        Country::create(['Alpha2Code' => 'IL', 'Alpha3Code' => 'ISR', 'NumericCode' => '376', 'Name' => 'Israel', 'PhoneCode' => '972']);
        Country::create(['Alpha2Code' => 'IT', 'Alpha3Code' => 'ITA', 'NumericCode' => '380', 'Name' => 'Italia', 'PhoneCode' => '39']);
        Country::create(['Alpha2Code' => 'JM', 'Alpha3Code' => 'JAM', 'NumericCode' => '388', 'Name' => 'Jamaica', 'PhoneCode' => '1-876']);
        Country::create(['Alpha2Code' => 'JE', 'Alpha3Code' => 'JEY', 'NumericCode' => '832', 'Name' => 'Jersey', 'PhoneCode' => '44']);
        Country::create(['Alpha2Code' => 'JO', 'Alpha3Code' => 'JOR', 'NumericCode' => '400', 'Name' => 'Jordania', 'PhoneCode' => '962']);
        Country::create(['Alpha2Code' => 'JP', 'Alpha3Code' => 'JPN', 'NumericCode' => '392', 'Name' => 'Japón', 'PhoneCode' => '81']);
        Country::create(['Alpha2Code' => 'KZ', 'Alpha3Code' => 'KAZ', 'NumericCode' => '398', 'Name' => 'Kazajistán', 'PhoneCode' => '7']);
        Country::create(['Alpha2Code' => 'KE', 'Alpha3Code' => 'KEN', 'NumericCode' => '404', 'Name' => 'Kenia', 'PhoneCode' => '254']);
        Country::create(['Alpha2Code' => 'KG', 'Alpha3Code' => 'KGZ', 'NumericCode' => '417', 'Name' => 'Kirguistán', 'PhoneCode' => '996']);
        Country::create(['Alpha2Code' => 'KH', 'Alpha3Code' => 'KHM', 'NumericCode' => '116', 'Name' => 'Camboya', 'PhoneCode' => '855']);
        Country::create(['Alpha2Code' => 'KI', 'Alpha3Code' => 'KIR', 'NumericCode' => '296', 'Name' => 'Kiribati', 'PhoneCode' => '686']);
        Country::create(['Alpha2Code' => 'KN', 'Alpha3Code' => 'KNA', 'NumericCode' => '659', 'Name' => 'San Cristóbal y Nieves', 'PhoneCode' => '1-869']);
        Country::create(['Alpha2Code' => 'KR', 'Alpha3Code' => 'KOR', 'NumericCode' => '410', 'Name' => 'Corea del Sur', 'PhoneCode' => '82']);
        Country::create(['Alpha2Code' => 'KW', 'Alpha3Code' => 'KWT', 'NumericCode' => '414', 'Name' => 'Kuweit', 'PhoneCode' => '965']);
        Country::create(['Alpha2Code' => 'LA', 'Alpha3Code' => 'LAO', 'NumericCode' => '418', 'Name' => 'Laos', 'PhoneCode' => '856']);
        Country::create(['Alpha2Code' => 'LB', 'Alpha3Code' => 'LBN', 'NumericCode' => '422', 'Name' => 'Libano', 'PhoneCode' => '961']);
        Country::create(['Alpha2Code' => 'LR', 'Alpha3Code' => 'LBR', 'NumericCode' => '430', 'Name' => 'Liberia', 'PhoneCode' => '231']);
        Country::create(['Alpha2Code' => 'LY', 'Alpha3Code' => 'LBY', 'NumericCode' => '434', 'Name' => 'Libia', 'PhoneCode' => '218']);
        Country::create(['Alpha2Code' => 'LC', 'Alpha3Code' => 'LCA', 'NumericCode' => '662', 'Name' => 'Santa Lucía', 'PhoneCode' => '1-758']);
        Country::create(['Alpha2Code' => 'LI', 'Alpha3Code' => 'LIE', 'NumericCode' => '438', 'Name' => 'Liechtenstein', 'PhoneCode' => '423']);
        Country::create(['Alpha2Code' => 'LK', 'Alpha3Code' => 'LKA', 'NumericCode' => '144', 'Name' => 'Sri Lanka', 'PhoneCode' => '94']);
        Country::create(['Alpha2Code' => 'LS', 'Alpha3Code' => 'LSO', 'NumericCode' => '426', 'Name' => 'Lesoto', 'PhoneCode' => '266']);
        Country::create(['Alpha2Code' => 'LT', 'Alpha3Code' => 'LTU', 'NumericCode' => '440', 'Name' => 'Lituania', 'PhoneCode' => '370']);
        Country::create(['Alpha2Code' => 'LU', 'Alpha3Code' => 'LUX', 'NumericCode' => '442', 'Name' => 'Luxemburgo', 'PhoneCode' => '352']);
        Country::create(['Alpha2Code' => 'LV', 'Alpha3Code' => 'LVA', 'NumericCode' => '428', 'Name' => 'Letonia', 'PhoneCode' => '371']);
        Country::create(['Alpha2Code' => 'MO', 'Alpha3Code' => 'MAC', 'NumericCode' => '446', 'Name' => 'Macao', 'PhoneCode' => '853']);
        Country::create(['Alpha2Code' => 'MF', 'Alpha3Code' => 'MAF', 'NumericCode' => '534', 'Name' => 'San Martín', 'PhoneCode' => '590']);
        Country::create(['Alpha2Code' => 'MA', 'Alpha3Code' => 'MAR', 'NumericCode' => '504', 'Name' => 'Marruecos', 'PhoneCode' => '212']);
        Country::create(['Alpha2Code' => 'MC', 'Alpha3Code' => 'MCO', 'NumericCode' => '492', 'Name' => 'Monaco', 'PhoneCode' => '377']);
        Country::create(['Alpha2Code' => 'MD', 'Alpha3Code' => 'MDA', 'NumericCode' => '498', 'Name' => 'Moldavia', 'PhoneCode' => '373']);
        Country::create(['Alpha2Code' => 'MG', 'Alpha3Code' => 'MDG', 'NumericCode' => '450', 'Name' => 'Madagascar', 'PhoneCode' => '261']);
        Country::create(['Alpha2Code' => 'MV', 'Alpha3Code' => 'MDV', 'NumericCode' => '462', 'Name' => 'Maldivas', 'PhoneCode' => '960']);
        Country::create(['Alpha2Code' => 'MX', 'Alpha3Code' => 'MEX', 'NumericCode' => '484', 'Name' => 'México', 'PhoneCode' => '52']);
        Country::create(['Alpha2Code' => 'MH', 'Alpha3Code' => 'MHL', 'NumericCode' => '584', 'Name' => 'Islas Marshall', 'PhoneCode' => '692']);
        Country::create(['Alpha2Code' => 'MK', 'Alpha3Code' => 'MKD', 'NumericCode' => '807', 'Name' => 'Macedonia', 'PhoneCode' => '389']);
        Country::create(['Alpha2Code' => 'ML', 'Alpha3Code' => 'MLI', 'NumericCode' => '466', 'Name' => 'Mali', 'PhoneCode' => '223']);
        Country::create(['Alpha2Code' => 'MT', 'Alpha3Code' => 'MLT', 'NumericCode' => '470', 'Name' => 'Malta', 'PhoneCode' => '356']);
        Country::create(['Alpha2Code' => 'MM', 'Alpha3Code' => 'MMR', 'NumericCode' => '104', 'Name' => 'Birmania', 'PhoneCode' => '95']);
        Country::create(['Alpha2Code' => 'ME', 'Alpha3Code' => 'MNE', 'NumericCode' => '499', 'Name' => 'Monténégro', 'PhoneCode' => '382']);
        Country::create(['Alpha2Code' => 'MN', 'Alpha3Code' => 'MNG', 'NumericCode' => '496', 'Name' => 'Mongolia', 'PhoneCode' => '976']);
        Country::create(['Alpha2Code' => 'MP', 'Alpha3Code' => 'MNP', 'NumericCode' => '580', 'Name' => 'Islas Marianas del Norte', 'PhoneCode' => '1-670']);
        Country::create(['Alpha2Code' => 'MZ', 'Alpha3Code' => 'MOZ', 'NumericCode' => '508', 'Name' => 'Mozambique', 'PhoneCode' => '258']);
        Country::create(['Alpha2Code' => 'MR', 'Alpha3Code' => 'MRT', 'NumericCode' => '478', 'Name' => 'Mauritania', 'PhoneCode' => '222']);
        Country::create(['Alpha2Code' => 'MS', 'Alpha3Code' => 'MSR', 'NumericCode' => '500', 'Name' => 'Montserrat', 'PhoneCode' => '1-664']);
        Country::create(['Alpha2Code' => 'MQ', 'Alpha3Code' => 'MTQ', 'NumericCode' => '474', 'Name' => 'Martinica', 'PhoneCode' => '596']);
        Country::create(['Alpha2Code' => 'MU', 'Alpha3Code' => 'MUS', 'NumericCode' => '480', 'Name' => 'Mauricio', 'PhoneCode' => '230']);
        Country::create(['Alpha2Code' => 'MW', 'Alpha3Code' => 'MWI', 'NumericCode' => '454', 'Name' => 'Malaui', 'PhoneCode' => '265']);
        Country::create(['Alpha2Code' => 'MY', 'Alpha3Code' => 'MYS', 'NumericCode' => '458', 'Name' => 'Malasia', 'PhoneCode' => '60']);
        Country::create(['Alpha2Code' => 'YT', 'Alpha3Code' => 'MYT', 'NumericCode' => '175', 'Name' => 'Mayotte', 'PhoneCode' => '262']);
        Country::create(['Alpha2Code' => 'NA', 'Alpha3Code' => 'NAM', 'NumericCode' => '516', 'Name' => 'Namibia', 'PhoneCode' => '264']);
        Country::create(['Alpha2Code' => 'NC', 'Alpha3Code' => 'NCL', 'NumericCode' => '540', 'Name' => 'Nueva Caledonia', 'PhoneCode' => '687']);
        Country::create(['Alpha2Code' => 'NE', 'Alpha3Code' => 'NER', 'NumericCode' => '562', 'Name' => 'Niger', 'PhoneCode' => '227']);
        Country::create(['Alpha2Code' => 'NF', 'Alpha3Code' => 'NFK', 'NumericCode' => '574', 'Name' => 'Isla Norfolk', 'PhoneCode' => '672']);
        Country::create(['Alpha2Code' => 'NG', 'Alpha3Code' => 'NGA', 'NumericCode' => '566', 'Name' => 'Nigeria', 'PhoneCode' => '234']);
        Country::create(['Alpha2Code' => 'NI', 'Alpha3Code' => 'NIC', 'NumericCode' => '558', 'Name' => 'Nicaragua', 'PhoneCode' => '505']);
        Country::create(['Alpha2Code' => 'NU', 'Alpha3Code' => 'NIU', 'NumericCode' => '570', 'Name' => 'Niue', 'PhoneCode' => '683']);
        Country::create(['Alpha2Code' => 'NL', 'Alpha3Code' => 'NLD', 'NumericCode' => '528', 'Name' => 'Países Bajos', 'PhoneCode' => '31']);
        Country::create(['Alpha2Code' => 'NO', 'Alpha3Code' => 'NOR', 'NumericCode' => '578', 'Name' => 'Noruega', 'PhoneCode' => '47']);
        Country::create(['Alpha2Code' => 'NP', 'Alpha3Code' => 'NPL', 'NumericCode' => '524', 'Name' => 'Nepal', 'PhoneCode' => '977']);
        Country::create(['Alpha2Code' => 'NR', 'Alpha3Code' => 'NRU', 'NumericCode' => '520', 'Name' => 'Nauru', 'PhoneCode' => '674']);
        Country::create(['Alpha2Code' => 'NZ', 'Alpha3Code' => 'NZL', 'NumericCode' => '554', 'Name' => 'Nueva Zelanda', 'PhoneCode' => '64']);
        Country::create(['Alpha2Code' => 'OM', 'Alpha3Code' => 'OMN', 'NumericCode' => '512', 'Name' => 'Omán', 'PhoneCode' => '968']);
        Country::create(['Alpha2Code' => 'PK', 'Alpha3Code' => 'PAK', 'NumericCode' => '586', 'Name' => 'Pakistán', 'PhoneCode' => '92']);
        Country::create(['Alpha2Code' => 'PA', 'Alpha3Code' => 'PAN', 'NumericCode' => '591', 'Name' => 'Panama', 'PhoneCode' => '507']);
        Country::create(['Alpha2Code' => 'PN', 'Alpha3Code' => 'PCN', 'NumericCode' => '612', 'Name' => 'Islas Pitcairn', 'PhoneCode' => '870']);
        Country::create(['Alpha2Code' => 'PE', 'Alpha3Code' => 'PER', 'NumericCode' => '604', 'Name' => 'Perú', 'PhoneCode' => '51']);
        Country::create(['Alpha2Code' => 'PH', 'Alpha3Code' => 'PHL', 'NumericCode' => '608', 'Name' => 'Filipinas', 'PhoneCode' => '63']);
        Country::create(['Alpha2Code' => 'PW', 'Alpha3Code' => 'PLW', 'NumericCode' => '585', 'Name' => 'Palaos', 'PhoneCode' => '680']);
        Country::create(['Alpha2Code' => 'PG', 'Alpha3Code' => 'PNG', 'NumericCode' => '598', 'Name' => 'Papúa Nueva Guinea', 'PhoneCode' => '675']);
        Country::create(['Alpha2Code' => 'PL', 'Alpha3Code' => 'POL', 'NumericCode' => '616', 'Name' => 'Polonia'   , 'PhoneCode' => '48']);
        Country::create(['Alpha2Code' => 'PR', 'Alpha3Code' => 'PRI', 'NumericCode' => '630', 'Name' => 'Puerto Rico', 'PhoneCode' => '1-787']);
        Country::create(['Alpha2Code' => 'KP', 'Alpha3Code' => 'PRK', 'NumericCode' => '408', 'Name' => 'Corea del Norte', 'PhoneCode' => '850']);
        Country::create(['Alpha2Code' => 'PT', 'Alpha3Code' => 'PRT', 'NumericCode' => '620', 'Name' => 'Portugal', 'PhoneCode' => '351']);
        Country::create(['Alpha2Code' => 'PY', 'Alpha3Code' => 'PRY', 'NumericCode' => '600', 'Name' => 'Paraguay', 'PhoneCode' => '595']);
        Country::create(['Alpha2Code' => 'PS', 'Alpha3Code' => 'PSE', 'NumericCode' => '275', 'Name' => 'Palestina', 'PhoneCode' => '970']);
        Country::create(['Alpha2Code' => 'PF', 'Alpha3Code' => 'PYF', 'NumericCode' => '258', 'Name' => 'Polinesia Francesa', 'PhoneCode' => '689']);
        Country::create(['Alpha2Code' => 'QA', 'Alpha3Code' => 'QAT', 'NumericCode' => '634', 'Name' => 'Catar', 'PhoneCode' => '974']);
        Country::create(['Alpha2Code' => 'RE', 'Alpha3Code' => 'REU', 'NumericCode' => '638', 'Name' => 'Reunión'   , 'PhoneCode' => '262']);
        Country::create(['Alpha2Code' => 'RO', 'Alpha3Code' => 'ROU', 'NumericCode' => '642', 'Name' => 'Rumania', 'PhoneCode' => '40']);
        Country::create(['Alpha2Code' => 'RU', 'Alpha3Code' => 'RUS', 'NumericCode' => '643', 'Name' => 'Rusia', 'PhoneCode' => '7']);
        Country::create(['Alpha2Code' => 'RW', 'Alpha3Code' => 'RWA', 'NumericCode' => '646', 'Name' => 'Ruanda', 'PhoneCode' => '250']);
        Country::create(['Alpha2Code' => 'SA', 'Alpha3Code' => 'SAU', 'NumericCode' => '682', 'Name' => 'Arabia Saudí', 'PhoneCode' => '966']);
        Country::create(['Alpha2Code' => 'SD', 'Alpha3Code' => 'SDN', 'NumericCode' => '729', 'Name' => 'Sudán'  , 'PhoneCode' => '249']);
        Country::create(['Alpha2Code' => 'SN', 'Alpha3Code' => 'SEN', 'NumericCode' => '686', 'Name' => 'Senegal', 'PhoneCode' => '221']);
        Country::create(['Alpha2Code' => 'SG', 'Alpha3Code' => 'SGP', 'NumericCode' => '702', 'Name' => 'Singapur', 'PhoneCode' => '65']);
        Country::create(['Alpha2Code' => 'GS', 'Alpha3Code' => 'SGS', 'NumericCode' => '239', 'Name' => 'Islas Georgias y Sandwich del Sur', 'PhoneCode' => '500']);
        Country::create(['Alpha2Code' => 'SH', 'Alpha3Code' => 'SHN', 'NumericCode' => '654', 'Name' => 'Sint Helena, Ascension and Tristan da Cunha', 'PhoneCode' => '290']);
        Country::create(['Alpha2Code' => 'SB', 'Alpha3Code' => 'SLB', 'NumericCode' => '90', 'Name' => 'Islas Salomón', 'PhoneCode' => '677']);
        Country::create(['Alpha2Code' => 'SL', 'Alpha3Code' => 'SLE', 'NumericCode' => '694', 'Name' => 'Sierra Leona', 'PhoneCode' => '232']);
        Country::create(['Alpha2Code' => 'SV', 'Alpha3Code' => 'SLV', 'NumericCode' => '222', 'Name' => 'El Salvador', 'PhoneCode' => '503']);
        Country::create(['Alpha2Code' => 'SM', 'Alpha3Code' => 'SMR', 'NumericCode' => '674', 'Name' => 'San Marino', 'PhoneCode' => '378']);
        Country::create(['Alpha2Code' => 'SO', 'Alpha3Code' => 'SOM', 'NumericCode' => '706', 'Name' => 'Somalia', 'PhoneCode' => '252']);  
        Country::create(['Alpha2Code' => 'PM', 'Alpha3Code' => 'SPM', 'NumericCode' => '666', 'Name' => 'San Pedro y Miquelón', 'PhoneCode' => '508']);
        Country::create(['Alpha2Code' => 'RS', 'Alpha3Code' => 'SRB', 'NumericCode' => '688', 'Name' => 'Serbia', 'PhoneCode' => '381']);
        Country::create(['Alpha2Code' => 'SS', 'Alpha3Code' => 'SSD', 'NumericCode' => '728', 'Name' => 'Sudán del Sur', 'PhoneCode' => '211']);
        Country::create(['Alpha2Code' => 'ST', 'Alpha3Code' => 'STP', 'NumericCode' => '678', 'Name' => 'Santo Tomé y Príncipe', 'PhoneCode' => '239']);
        Country::create(['Alpha2Code' => 'SR', 'Alpha3Code' => 'SUR', 'NumericCode' => '740', 'Name' => 'Surinam', 'PhoneCode' => '597']);
        Country::create(['Alpha2Code' => 'SK', 'Alpha3Code' => 'SVK', 'NumericCode' => '703', 'Name' => 'Eslovaquia', 'PhoneCode' => '421']);
        Country::create(['Alpha2Code' => 'SI', 'Alpha3Code' => 'SVN', 'NumericCode' => '705', 'Name' => 'Eslovenia', 'PhoneCode' => '386']);
        Country::create(['Alpha2Code' => 'SE', 'Alpha3Code' => 'SWE', 'NumericCode' => '752', 'Name' => 'Suecia', 'PhoneCode' => '46']);
        Country::create(['Alpha2Code' => 'SZ', 'Alpha3Code' => 'SWZ', 'NumericCode' => '748', 'Name' => 'eSwatani', 'PhoneCode' => '268']);
        Country::create(['Alpha2Code' => 'SX', 'Alpha3Code' => 'SXM', 'NumericCode' => '663', 'Name' => 'Sint-Maarten', 'PhoneCode' => '1-721']);
        Country::create(['Alpha2Code' => 'SC', 'Alpha3Code' => 'SYC', 'NumericCode' => '690', 'Name' => 'Seychelles', 'PhoneCode' => '248']);
        Country::create(['Alpha2Code' => 'SY', 'Alpha3Code' => 'SYR', 'NumericCode' => '760', 'Name' => 'Siria', 'PhoneCode' => '963']);
        Country::create(['Alpha2Code' => 'TC', 'Alpha3Code' => 'TCA', 'NumericCode' => '796', 'Name' => 'Islas Turcas y Caicos', 'PhoneCode' => '1-649']);
        Country::create(['Alpha2Code' => 'TD', 'Alpha3Code' => 'TCD', 'NumericCode' => '148', 'Name' => 'Chad', 'PhoneCode' => '235']);
        Country::create(['Alpha2Code' => 'TG', 'Alpha3Code' => 'TGO', 'NumericCode' => '768', 'Name' => 'Togo', 'PhoneCode' => '228']);
        Country::create(['Alpha2Code' => 'TH', 'Alpha3Code' => 'THA', 'NumericCode' => '764', 'Name' => 'Tailandia', 'PhoneCode' => '66']);
        Country::create(['Alpha2Code' => 'TJ', 'Alpha3Code' => 'TJK', 'NumericCode' => '762', 'Name' => 'Tayikistán', 'PhoneCode' => '992']);
        Country::create(['Alpha2Code' => 'TK', 'Alpha3Code' => 'TKL', 'NumericCode' => '772', 'Name' => 'Tokelau', 'PhoneCode' => '690']);
        Country::create(['Alpha2Code' => 'TM', 'Alpha3Code' => 'TKM', 'NumericCode' => '795', 'Name' => 'Turkmenistán', 'PhoneCode' => '993']);
        Country::create(['Alpha2Code' => 'TL', 'Alpha3Code' => 'TLS', 'NumericCode' => '626', 'Name' => 'Timor Oriental', 'PhoneCode' => '670']);
        Country::create(['Alpha2Code' => 'TO', 'Alpha3Code' => 'TON', 'NumericCode' => '776', 'Name' => 'Tonga', 'PhoneCode' => '676']);
        Country::create(['Alpha2Code' => 'TT', 'Alpha3Code' => 'TTO', 'NumericCode' => '780', 'Name' => 'Trinidad y Tobago', 'PhoneCode' => '1-868']);
        Country::create(['Alpha2Code' => 'TN', 'Alpha3Code' => 'TUN', 'NumericCode' => '788', 'Name' => 'Túnez', 'PhoneCode' => '216']);
        Country::create(['Alpha2Code' => 'TR', 'Alpha3Code' => 'TUR', 'NumericCode' => '792', 'Name' => 'Turquía', 'PhoneCode' => '90']);
        Country::create(['Alpha2Code' => 'TV', 'Alpha3Code' => 'TUV', 'NumericCode' => '798', 'Name' => 'Tuvalu', 'PhoneCode' => '688']);
        Country::create(['Alpha2Code' => 'TW', 'Alpha3Code' => 'TWN', 'NumericCode' => '158', 'Name' => 'Taiwan', 'PhoneCode' => '886']);
        Country::create(['Alpha2Code' => 'TZ', 'Alpha3Code' => 'TZA', 'NumericCode' => '834', 'Name' => 'Tanzania', 'PhoneCode' => '255']);
        Country::create(['Alpha2Code' => 'UG', 'Alpha3Code' => 'UGA', 'NumericCode' => '800', 'Name' => 'Uganda', 'PhoneCode' => '256']);
        Country::create(['Alpha2Code' => 'UA', 'Alpha3Code' => 'UKR', 'NumericCode' => '804', 'Name' => 'Ucrania', 'PhoneCode' => '380']);
        Country::create(['Alpha2Code' => 'UY', 'Alpha3Code' => 'URY', 'NumericCode' => '858', 'Name' => 'Uruguay', 'PhoneCode' => '598']);
        Country::create(['Alpha2Code' => 'US', 'Alpha3Code' => 'USA', 'NumericCode' => '840', 'Name' => 'Estados Unidos', 'PhoneCode' => '1']);
        Country::create(['Alpha2Code' => 'UZ', 'Alpha3Code' => 'UZB', 'NumericCode' => '860', 'Name' => 'Uzbekistán', 'PhoneCode' => '998']);
        Country::create(['Alpha2Code' => 'VA', 'Alpha3Code' => 'VAT', 'NumericCode' => '336', 'Name' => 'Vaticano', 'PhoneCode' => '379']);
        Country::create(['Alpha2Code' => 'VC', 'Alpha3Code' => 'VCT', 'NumericCode' => '670', 'Name' => 'San Vicente y las Granadinas', 'PhoneCode' => '1-784']);
        Country::create(['Alpha2Code' => 'VE', 'Alpha3Code' => 'VEN', 'NumericCode' => '862', 'Name' => 'Venezuela', 'PhoneCode' => '58']);
        Country::create(['Alpha2Code' => 'VG', 'Alpha3Code' => 'VGB', 'NumericCode' => '92', 'Name' => 'Islas Vírgenes Británicas', 'PhoneCode' => '1-284']);
        Country::create(['Alpha2Code' => 'VI', 'Alpha3Code' => 'VIR', 'NumericCode' => '850', 'Name' => 'Islas Vírgenes de los Estados Unidos', 'PhoneCode' => '1-340']);
        Country::create(['Alpha2Code' => 'VN', 'Alpha3Code' => 'VNM', 'NumericCode' => '704', 'Name' => 'Vietnam', 'PhoneCode' => '84']);
        Country::create(['Alpha2Code' => 'VU', 'Alpha3Code' => 'VUT', 'NumericCode' => '548', 'Name' => 'Vanuatu', 'PhoneCode' => '678']);
        Country::create(['Alpha2Code' => 'WF', 'Alpha3Code' => 'WLF', 'NumericCode' => '876', 'Name' => 'Wallis y Futuna', 'PhoneCode' => '681']);
        Country::create(['Alpha2Code' => 'WS', 'Alpha3Code' => 'WSM', 'NumericCode' => '882', 'Name' => 'Samoa', 'PhoneCode' => '685']);
        Country::create(['Alpha2Code' => 'XK', 'Alpha3Code' => 'XKX', 'NumericCode' => '153', 'Name' => 'Kosovo', 'PhoneCode' => '383']);
        Country::create(['Alpha2Code' => 'YE', 'Alpha3Code' => 'YEM', 'NumericCode' => '887', 'Name' => 'Yemen', 'PhoneCode' => '967']);
        Country::create(['Alpha2Code' => 'ZA', 'Alpha3Code' => 'ZAF', 'NumericCode' => '710', 'Name' => 'Sudáfrica', 'PhoneCode' => '27']);
        Country::create(['Alpha2Code' => 'ZM', 'Alpha3Code' => 'ZMB', 'NumericCode' => '894', 'Name' => 'Zambia', 'PhoneCode' => '260']);
        Country::create(['Alpha2Code' => 'ZW', 'Alpha3Code' => 'ZWE', 'NumericCode' => '716', 'Name' => 'Zimbabwe', 'PhoneCode' => '263']);
    }
}
